---------------------------------------------------------
-- Export file for user USR_DENENLINEA_APP@TELEPOLDESA --
-- Created by WilMor on 10/08/2018, 19:03:13 19:03:13  --
---------------------------------------------------------

set define off
spool AppDBInformante.log

prompt
prompt Creating table APP_VI_INFORMANTS
prompt ================================
prompt
create table APP_VI_INFORMANTS
(
  informant_id NUMBER generated by default on null as identity (nocache),
  first_name   VARCHAR2(50) not null,
  last_name    VARCHAR2(50),
  email        VARCHAR2(50),
  phone_number VARCHAR2(20)
)
;
comment on column APP_VI_INFORMANTS.informant_id
  is 'Primary key';
alter table APP_VI_INFORMANTS
  add constraint APP_VI_INFORMANTS_PK primary key (INFORMANT_ID);

prompt
prompt Creating table APP_VI_CRIMES
prompt ============================
prompt
create table APP_VI_CRIMES
(
  crime_id          NUMBER generated by default on null as identity (nocache),
  description       VARCHAR2(500) not null,
  legal_information VARCHAR2(100)
)
;
comment on column APP_VI_CRIMES.crime_id
  is 'Primary key';
alter table APP_VI_CRIMES
  add constraint APP_VI_CRIMES_PK primary key (CRIME_ID);

prompt
prompt Creating table APP_VI_INVESTIGATIONS
prompt ====================================
prompt
create table APP_VI_INVESTIGATIONS
(
  investigation_id NUMBER generated by default on null as identity (nocache),
  crime_id         NUMBER not null,
  nunc             VARCHAR2(20) not null,
  title            VARCHAR2(50) not null,
  description      VARCHAR2(3000) not null,
  state            VARCHAR2(50) not null,
  city             VARCHAR2(50) not null,
  crime_date       DATE default sysdate,
  status           NUMBER default 1
)
;
comment on table APP_VI_INVESTIGATIONS
  is 'Investigations en App Virtual Informant';
comment on column APP_VI_INVESTIGATIONS.investigation_id
  is 'Primary key';
comment on column APP_VI_INVESTIGATIONS.crime_date
  is 'Fecha ocurrencia de hechos';
comment on column APP_VI_INVESTIGATIONS.status
  is 'Estado de la investigación';
alter table APP_VI_INVESTIGATIONS
  add constraint APP_VI_INVESTIGATIONS_PK primary key (INVESTIGATION_ID);
alter table APP_VI_INVESTIGATIONS
  add constraint APP_VI_INVESTIGATIONS_CRIME_FK foreign key (CRIME_ID)
  references APP_VI_CRIMES (CRIME_ID);

prompt
prompt Creating table APP_VI_CONTRIBUTIONS
prompt ===================================
prompt
create table APP_VI_CONTRIBUTIONS
(
  contribution_id  NUMBER generated by default on null as identity (nocache),
  investigation_id NUMBER not null,
  description      VARCHAR2(4000),
  informant_id     NUMBER
)
;
comment on column APP_VI_CONTRIBUTIONS.contribution_id
  is 'Primary key';
alter table APP_VI_CONTRIBUTIONS
  add constraint APP_VI_CONTRIBUTIONS_PK primary key (CONTRIBUTION_ID);
alter table APP_VI_CONTRIBUTIONS
  add constraint APP_VI_CONTRIBUTIONS_INFO_FK foreign key (INFORMANT_ID)
  references APP_VI_INFORMANTS (INFORMANT_ID);
alter table APP_VI_CONTRIBUTIONS
  add constraint APP_VI_CONTRIBUTIONS_INV_FK foreign key (INVESTIGATION_ID)
  references APP_VI_INVESTIGATIONS (INVESTIGATION_ID);

prompt
prompt Creating table APP_VI_CONTRIBUTIONS_FILES
prompt =========================================
prompt
create table APP_VI_CONTRIBUTIONS_FILES
(
  contribution_file_id NUMBER generated by default on null as identity (nocache),
  contribution_id      NUMBER not null,
  path                 VARCHAR2(500) not null,
  content_type         VARCHAR2(50) not null,
  file_doc             BLOB
)
;
comment on column APP_VI_CONTRIBUTIONS_FILES.contribution_file_id
  is 'Primary key';
comment on column APP_VI_CONTRIBUTIONS_FILES.file_doc
  is 'Archivo';
alter table APP_VI_CONTRIBUTIONS_FILES
  add constraint APP_VI_CONTRIBUTIONS_FILES_PK primary key (CONTRIBUTION_FILE_ID);
alter table APP_VI_CONTRIBUTIONS_FILES
  add constraint APP_VI_CONTRIBUTIONS_FILES__FK foreign key (CONTRIBUTION_ID)
  references APP_VI_CONTRIBUTIONS (CONTRIBUTION_ID);

prompt
prompt Creating table APP_VI_INVESTIGATORS
prompt ===================================
prompt
create table APP_VI_INVESTIGATORS
(
  investigator_id NUMBER generated by default on null as identity (nocache),
  first_name      VARCHAR2(50) not null,
  last_name       VARCHAR2(50) not null,
  institution     VARCHAR2(50) not null
)
;
comment on column APP_VI_INVESTIGATORS.investigator_id
  is 'Primary key';
alter table APP_VI_INVESTIGATORS
  add constraint APP_VI_INVESTIGATORS_PK primary key (INVESTIGATOR_ID);

prompt
prompt Creating table APP_VI_INVESTIGA_INVESTIGATORS
prompt =============================================
prompt
create table APP_VI_INVESTIGA_INVESTIGATORS
(
  investigation_investigator_id NUMBER generated by default on null as identity (nocache),
  investigation_id              NUMBER not null,
  investigator_id               NUMBER,
  is_active                     NUMBER default 1 not null
)
;
alter table APP_VI_INVESTIGA_INVESTIGATORS
  add constraint APP_VI_INVESTIGATIONS_INVES_PK primary key (INVESTIGATION_INVESTIGATOR_ID);
alter table APP_VI_INVESTIGA_INVESTIGATORS
  add constraint APP_VI_INVESTIGA_INVESTIGAT_FK foreign key (INVESTIGATION_ID)
  references APP_VI_INVESTIGATIONS (INVESTIGATION_ID);
alter table APP_VI_INVESTIGA_INVESTIGATORS
  add constraint APP_VI_INVEST_INVESTIGATOR_FK foreign key (INVESTIGATOR_ID)
  references APP_VI_INVESTIGATORS (INVESTIGATOR_ID);

prompt
prompt Creating table APP_VI_INVESTIGATION_FILES
prompt =========================================
prompt
create table APP_VI_INVESTIGATION_FILES
(
  investigation_file_id NUMBER generated by default on null as identity (nocache),
  investigation_id      NUMBER not null,
  path                  VARCHAR2(500) not null,
  content_type          VARCHAR2(50) not null,
  file_doc              BLOB
)
;
comment on column APP_VI_INVESTIGATION_FILES.investigation_file_id
  is 'Primary key';
comment on column APP_VI_INVESTIGATION_FILES.file_doc
  is 'Archivo';
alter table APP_VI_INVESTIGATION_FILES
  add constraint APP_VI_INVESTIGATION_FILES_PK primary key (INVESTIGATION_FILE_ID);
alter table APP_VI_INVESTIGATION_FILES
  add constraint APP_VI_INVESTIGA_FILE_INV_FK foreign key (INVESTIGATION_ID)
  references APP_VI_INVESTIGATIONS (INVESTIGATION_ID);


spool off
