//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsInformante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_VI_INFORMANTS
    {
        public APP_VI_INFORMANTS()
        {
            this.APP_VI_CONTRIBUTIONS = new HashSet<APP_VI_CONTRIBUTIONS>();
        }
    
        public decimal INFORMANT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL { get; set; }
        public string PHONE_NUMBER { get; set; }
    
        public virtual ICollection<APP_VI_CONTRIBUTIONS> APP_VI_CONTRIBUTIONS { get; set; }
    }
}
