//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsInformante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_VI_CONTRIBUTIONS_FILES
    {
        public decimal CONTRIBUTION_FILE_ID { get; set; }
        public decimal CONTRIBUTION_ID { get; set; }
        public string PATH { get; set; }
        public string CONTENT_TYPE { get; set; }
    
        public virtual APP_VI_CONTRIBUTIONS APP_VI_CONTRIBUTIONS { get; set; }
    }
}
