//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsInformante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_VI_INVESTIGATION_FILES
    {
        public decimal INVESTIGATION_FILE_ID { get; set; }
        public decimal INVESTIGATION_ID { get; set; }
        public string PATH { get; set; }
        public string CONTENT_TYPE { get; set; }
    
        public virtual APP_VI_INVESTIGATIONS APP_VI_INVESTIGATIONS { get; set; }
    }
}
