//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsInformante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_VI_INVESTIGATORS
    {
        public APP_VI_INVESTIGATORS()
        {
            this.APP_VI_INVESTIGA_INVESTIGATORS = new HashSet<APP_VI_INVESTIGA_INVESTIGATORS>();
        }
    
        public decimal INVESTIGATOR_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string INSTITUTION { get; set; }
    
        public virtual ICollection<APP_VI_INVESTIGA_INVESTIGATORS> APP_VI_INVESTIGA_INVESTIGATORS { get; set; }
    }
}
