//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsInformante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_VI_INVESTIGA_INVESTIGATORS
    {
        public decimal INVESTIGATION_INVESTIGATOR_ID { get; set; }
        public decimal INVESTIGATION_ID { get; set; }
        public Nullable<decimal> INVESTIGATOR_ID { get; set; }
        public decimal IS_ACTIVE { get; set; }
    
        public virtual APP_VI_INVESTIGATORS APP_VI_INVESTIGATORS { get; set; }
        public virtual APP_VI_INVESTIGATIONS APP_VI_INVESTIGATIONS { get; set; }
    }
}
