//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsInformante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_VI_CRIMES
    {
        public APP_VI_CRIMES()
        {
            this.APP_VI_INVESTIGATIONS = new HashSet<APP_VI_INVESTIGATIONS>();
        }
    
        public decimal CRIME_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string LEGAL_INFORMATION { get; set; }
    
        public virtual ICollection<APP_VI_INVESTIGATIONS> APP_VI_INVESTIGATIONS { get; set; }
    }
}
