//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsInformante.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    //[Serializable]
    public partial class APP_VI_INVESTIGATIONS
    {
        public APP_VI_INVESTIGATIONS()
        {
            this.APP_VI_CONTRIBUTIONS = new HashSet<APP_VI_CONTRIBUTIONS>();
            this.APP_VI_INVESTIGA_INVESTIGATORS = new HashSet<APP_VI_INVESTIGA_INVESTIGATORS>();
            this.APP_VI_INVESTIGATION_FILES = new HashSet<APP_VI_INVESTIGATION_FILES>();
        }
    
        public decimal INVESTIGATION_ID { get; set; }
        public decimal CRIME_ID { get; set; }
        public string NUNC { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATE { get; set; }
        public string CITY { get; set; }
    
        public virtual ICollection<APP_VI_CONTRIBUTIONS> APP_VI_CONTRIBUTIONS { get; set; }
        public virtual APP_VI_CRIMES APP_VI_CRIMES { get; set; }
        public virtual ICollection<APP_VI_INVESTIGA_INVESTIGATORS> APP_VI_INVESTIGA_INVESTIGATORS { get; set; }
        public virtual ICollection<APP_VI_INVESTIGATION_FILES> APP_VI_INVESTIGATION_FILES { get; set; }
    }
}
