//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsInformante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_VI_INVESTIGATORS
    {
        public APP_VI_INVESTIGATORS()
        {
            this.APP_VI_INVESTIGA_INVESTIGATORS = new HashSet<APP_VI_INVESTIGA_INVESTIGATORS>();
        }
    
        public decimal INVESTIGATOR_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string INSTITUTION { get; set; }
    
        public virtual ICollection<APP_VI_INVESTIGA_INVESTIGATORS> APP_VI_INVESTIGA_INVESTIGATORS { get; set; }
    }
}
