//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsInformante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_VI_CONTRIBUTIONS
    {
        public APP_VI_CONTRIBUTIONS()
        {
            this.APP_VI_CONTRIBUTIONS_FILES = new HashSet<APP_VI_CONTRIBUTIONS_FILES>();
        }
    
        public decimal CONTRIBUTION_ID { get; set; }
        public decimal INVESTIGATION_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> INFORMANT_ID { get; set; }
    
        public virtual APP_VI_INFORMANTS APP_VI_INFORMANTS { get; set; }
        public virtual APP_VI_INVESTIGATIONS APP_VI_INVESTIGATIONS { get; set; }
        public virtual ICollection<APP_VI_CONTRIBUTIONS_FILES> APP_VI_CONTRIBUTIONS_FILES { get; set; }
    }
}
