//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsInformante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_VI_INVESTIGA_INVESTIGATORS
    {
        public decimal INVESTIGATION_INVESTIGATOR_ID { get; set; }
        public decimal INVESTIGATION_ID { get; set; }
        public Nullable<decimal> INVESTIGATOR_ID { get; set; }
        public decimal IS_ACTIVE { get; set; }
    
        public virtual APP_VI_INVESTIGATORS APP_VI_INVESTIGATORS { get; set; }
        public virtual APP_VI_INVESTIGATIONS APP_VI_INVESTIGATIONS { get; set; }
    }
}
