//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsInformante.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesInformante : DbContext
    {
        public EntitiesInformante()
            : base("name=EntitiesInformante")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APP_VI_CONTRIBUTIONS> APP_VI_CONTRIBUTIONS { get; set; }
        public DbSet<APP_VI_CONTRIBUTIONS_FILES> APP_VI_CONTRIBUTIONS_FILES { get; set; }
        public DbSet<APP_VI_CRIMES> APP_VI_CRIMES { get; set; }
        public DbSet<APP_VI_INFORMANTS> APP_VI_INFORMANTS { get; set; }
        public DbSet<APP_VI_INVESTIGA_INVESTIGATORS> APP_VI_INVESTIGA_INVESTIGATORS { get; set; }
        public DbSet<APP_VI_INVESTIGATION_FILES> APP_VI_INVESTIGATION_FILES { get; set; }
        public DbSet<APP_VI_INVESTIGATIONS> APP_VI_INVESTIGATIONS { get; set; }
        public DbSet<APP_VI_INVESTIGATORS> APP_VI_INVESTIGATORS { get; set; }
    }
}
